server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://sql6.freesqldatabase.com:3306/sql6702346
    username: sql6702346
    password: <password>
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: localhost
    port: 6379
    time-to-live: 3600